<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\joshu\Projects\STPurattofomu\static\models\HoshinoSwimsuit.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName =
    | 'Cafe_Idle'
    | 'Cafe_Reaction'
    | 'Cafe_Walk'
    | 'Formation_Idle'
    | 'Formation_Pickup'
    | 'Move_End_Normal01'
    | 'Move_End_Normal02'
    | 'Move_Ing01'
    | 'Move_Ing02'
    | 'Move_Jump01'
    | 'Move_Jump02'
    | 'Normal_Attack01_Delay'
    | 'Normal_Attack01_End'
    | 'Normal_Attack01_Ing'
    | 'Normal_Attack01_Start'
    | 'Normal_Attack02_Delay'
    | 'Normal_Attack02_End'
    | 'Normal_Attack02_Ing'
    | 'Normal_Attack02_Start'
    | 'Normal_Callsign'
    | 'Normal_Callsign_Random'
    | 'Normal_Idle01'
    | 'Normal_Idle02'
    | 'Normal_Reload01'
    | 'Normal_Reload02'
    | 'Normal_Reload02_Random'
    | 'Victory_End'
    | 'Victory_End_Random'
    | 'Victory_Start'
    | 'Victory_Start_Random'
    | 'Vital_Death01'
    | 'Vital_Death02'
    | 'Vital_Dying_ing01'
    | 'Vital_Dying_ing02'
    | 'Vital_Panic01'
    | 'Vital_Panic02'
    | 'Vital_Retreat01'
    | 'Vital_Retreat02'
    | 'fire_01|Hoshino_Swimsuit_Normal_Attack01_Start|Base Layer'
    | 'fire_02|Hoshino_Swimsuit_Normal_Attack01_Start|Base Layer'
    | 'Camera001|Hoshino_Swimsuit_Exs_Cutin_Cam|Base Layer'
    | 'Camera001.Target|Hoshino_Swimsuit_Exs_Cutin_Cam|Base Layer'
  type GLTFResult = {
    nodes: {
      Hoshino_Swimsuit_BeachProp_Outline_1: THREE.SkinnedMesh
      Hoshino_Swimsuit_BeachProp_Outline_2: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body_1: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body_2: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body_3: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body_4: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body_5: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body01: THREE.SkinnedMesh
      Hoshino_Swimsuit_Body02: THREE.SkinnedMesh
      Hoshino_Swimsuit_Weapon: THREE.SkinnedMesh
      Hoshino_Swimsuit_Halo: THREE.Mesh
      Bip001: THREE.Bone
      bone_AccRoot: THREE.Bone
    }
    materials: {
      Hoshino_Swimsuit_BeachProp: THREE.MeshStandardMaterial
      Hoshino_Swimsuit_BeachProp_Alpha: THREE.MeshStandardMaterial
      Hoshino_Swimsuit_Body: THREE.MeshStandardMaterial
      Hoshino_Original_Face: THREE.MeshStandardMaterial
      Hoshino_Swimsuit_EyeMouth: THREE.MeshStandardMaterial
      Hoshino_Swimsuit_Hair: THREE.MeshStandardMaterial
      Hoshino_Swimsuit_Eyebrow: THREE.MeshStandardMaterial
      Hoshino_Original_Weapon: THREE.MeshStandardMaterial
      Hoshino_Original_Halo: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/HoshinoSwimsuit.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Hoshino_Swimsuit" rotation={[Math.PI / 2, 0, 0]}>
        <T.Group name="bone_root" rotation={[-Math.PI / 2, 0, 0]}>
          <T is={gltf.nodes.Bip001} />
          <T is={gltf.nodes.bone_AccRoot} />
          <T.Group name="FX_Hoshino_Swimsuit_Formation_Pickup_Emotion_01">
            <T.Group name="Par" position={[-0.02, 0.54, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.9} />
            <T.Group name="Particle_System" position={[-0.01, 0.55, 0]} rotation={[Math.PI / 2, 0, 0]} />
          </T.Group>
          <T.Group name="FX_Hoshino_Swimsuit_Formation_Pickup_Emotion_02">
            <T.Group name="Particle_System001" position={[-0.36, 0.43, 0]} rotation={[-Math.PI / 2, -0.34, 0]} />
          </T.Group>
          <T.Group name="Hoshino_Swimsuit_BeachProp_Outline">
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_BeachProp_Outline_1"
              geometry={gltf.nodes.Hoshino_Swimsuit_BeachProp_Outline_1.geometry}
              material={gltf.materials.Hoshino_Swimsuit_BeachProp}
              skeleton={gltf.nodes.Hoshino_Swimsuit_BeachProp_Outline_1.skeleton}
            />
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_BeachProp_Outline_2"
              geometry={gltf.nodes.Hoshino_Swimsuit_BeachProp_Outline_2.geometry}
              material={gltf.materials.Hoshino_Swimsuit_BeachProp_Alpha}
              skeleton={gltf.nodes.Hoshino_Swimsuit_BeachProp_Outline_2.skeleton}
            />
          </T.Group>
          <T.Group name="Hoshino_Swimsuit_Body">
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_Body_1"
              geometry={gltf.nodes.Hoshino_Swimsuit_Body_1.geometry}
              material={gltf.materials.Hoshino_Swimsuit_Body}
              skeleton={gltf.nodes.Hoshino_Swimsuit_Body_1.skeleton}
            />
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_Body_2"
              geometry={gltf.nodes.Hoshino_Swimsuit_Body_2.geometry}
              material={gltf.materials.Hoshino_Original_Face}
              skeleton={gltf.nodes.Hoshino_Swimsuit_Body_2.skeleton}
            />
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_Body_3"
              geometry={gltf.nodes.Hoshino_Swimsuit_Body_3.geometry}
              material={gltf.materials.Hoshino_Swimsuit_EyeMouth}
              skeleton={gltf.nodes.Hoshino_Swimsuit_Body_3.skeleton}
            />
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_Body_4"
              geometry={gltf.nodes.Hoshino_Swimsuit_Body_4.geometry}
              material={gltf.materials.Hoshino_Swimsuit_Hair}
              skeleton={gltf.nodes.Hoshino_Swimsuit_Body_4.skeleton}
            />
            <T.SkinnedMesh
              name="Hoshino_Swimsuit_Body_5"
              geometry={gltf.nodes.Hoshino_Swimsuit_Body_5.geometry}
              material={gltf.materials.Hoshino_Swimsuit_Eyebrow}
              skeleton={gltf.nodes.Hoshino_Swimsuit_Body_5.skeleton}
            />
          </T.Group>
          <T.SkinnedMesh
            name="Hoshino_Swimsuit_Body01"
            geometry={gltf.nodes.Hoshino_Swimsuit_Body01.geometry}
            material={gltf.materials.Hoshino_Swimsuit_Body}
            skeleton={gltf.nodes.Hoshino_Swimsuit_Body01.skeleton}
          />
          <T.SkinnedMesh
            name="Hoshino_Swimsuit_Body02"
            geometry={gltf.nodes.Hoshino_Swimsuit_Body02.geometry}
            material={gltf.materials.Hoshino_Swimsuit_Body}
            skeleton={gltf.nodes.Hoshino_Swimsuit_Body02.skeleton}
          />
          <T.SkinnedMesh
            name="Hoshino_Swimsuit_Weapon"
            geometry={gltf.nodes.Hoshino_Swimsuit_Weapon.geometry}
            material={gltf.materials.Hoshino_Original_Weapon}
            skeleton={gltf.nodes.Hoshino_Swimsuit_Weapon.skeleton}
          />
        </T.Group>
        <T.Group name="EX_Root">
          <T.Group name="FX_Local_DM">
            <T.Group
              name="EX1_1"
              position={[-3.18, 3.11, 2.12]}
              rotation={[-0.45, 0.46, -0.46]}
              scale={[1, 0.77, 0.79]}
            />
            <T.Group name="EX1_2" />
            <T.Group name="EX1_3" />
            <T.Group name="EX1_4" />
          </T.Group>
          <T.Group name="Hoshino_Swimsuit_Exs_Cutin_Cam">
            <T.Group name="Camera001" position={[0.61, 27.37, 8.98]} rotation={[0.44, -0.02, -1.61]} />
            <T.Group name="Camera001Target" position={[-0.46, 1.31, -3.36]} rotation={[0, 0, Math.PI / 2]} />
            <T.Group name="Bloom" />
            <T.Group name="Choma" />
            <T.Group name="Directional_Light" position={[-0.96, 0.43, -2.5]} rotation={[-1.88, 1.28, -2.78]} />
            <T.Group name="DOF2" />
            <T.Group name="GameObject" />
            <T.Group name="Highlight" />
            <T.Group name="OtherPPV" />
          </T.Group>
        </T.Group>
        <T.Group name="HaloRoot" position={[0, -0.2, -1.03]}>
          <T.Mesh
            name="Hoshino_Swimsuit_Halo"
            geometry={gltf.nodes.Hoshino_Swimsuit_Halo.geometry}
            material={gltf.materials.Hoshino_Original_Halo}
            position={[0, 0.2, 1.03]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
